### PR TITLE
fix: Home screen site filtering by project

### LINKED ISSUE #673: Sites List has wrong filter options
### App Version

59

### Account

_No response_

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

The sites list filter menu should not have "Sort projects by" and should have "Filter sites by project." 
The "Filter sites by role" option should stay as-is.

image

### Steps to Reproduce

Tap the filter button on the sites list

### Expected behavior

image

### Actual behavior

image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by david-code**
## Description

This fixes the home screen sites list to allow filtering by project. It also fixes a few styling issues.

### Checklist
- [x] Corresponding issue has been opened
- [ ] New tests added

### Related Issues
Fixes #673

### CODE REVIEW

File: dev-client/src/components/home/BottomSheet.tsx [hunk 1]
```diff
@@ -190,13 +201,21 @@ const SiteFilterModal = ({useDistance}: ModalProps) => {
...
+      <SelectFilter
+        label={t('site.search.sort.label') + ':'}
         options={sortOptions}
         name="sort"
         nullableOption={t('general.filter.no_sort')}
       />
+
       <SelectFilter
-        label={t('site.search.filter_role')}
+        label={t('site.search.filter_role') + ':'}
```
Comment (paulschreiber) [inline dev-client/src/components/home/BottomSheet.tsx:218]: issue: the colon should be in the i18n string, because it needs localizing, too. i.e. in French we may need a space before the colon.

I see that it was removed — what was the reasoning for that?

Comment (david-code) [reply dev-client/src/components/home/BottomSheet.tsx:218]: Oh, I didn't know that. I saw it was inconsistent, with some strings having a colon and others not, so I added it here.

**Review by paulschreiber — APPROVED** [review]

**Comment by paulschreiber** [comment]
@david-code Please update `BottomSheet.tsx` to remove the colons.

**Comment by david-code** [comment]
> @david-code Please update `BottomSheet.tsx` to remove the colons.

They were removed in the most recent commit.
