### PR TITLE
fix: update lat/lon of create site form as user's location changes

### LINKED ISSUE #256: Add GPS refresh to Create Site form
The Create Site form needs a way to refresh the GPS coords when the user moves around.

### PR DESCRIPTION
**Pull request by shrouxm**
## Description
Moves the logic that updates user's location to the root of the app, and modifies the create site form to keep the lat/lon fields updated as the user moves.

### Checklist
- [x] Corresponding issue has been opened

### Related Issues
Fixes #256

### Verification steps
Latitude/longitude field of create site form should update as user moves around.

### CODE REVIEW

File: dev-client/src/components/sites/CreateSiteView.tsx [hunk 1]
```diff
@@ -55,25 +53,24 @@ type LocationInputOptions = 'coords' | 'gps' | 'pin';
 
 export default function CreateSiteView({
   defaultProject,
-  userLocation,
   createSiteCallback,
   sitePin,
 }: Props) {
   const {t} = useTranslation();
 
+  const userLocation = useSelector(state => state.map.userLocation);
```
Comment (david-code) [inline dev-client/src/components/sites/CreateSiteView.tsx:61]: comment: Mostly just curious, is there a reason why you moved the selector down to this component? I prefer to pass the location down as a prop, and have the screen be the one pulling in the global state with a selector.

**Review by david-code — APPROVED** [review]
Looks good!

File: dev-client/src/components/sites/CreateSiteView.tsx (hunk 1 above)
Comment (shrouxm) [reply dev-client/src/components/sites/CreateSiteView.tsx:61]: i usually default to pushing hook usages as far down as possible if they can trigger a re-render and to avoid repetitive parameter passing, but it's one of those weird squishy intuitive things i think
